version: '3.8'

services:
  es-master-1:
    image: elasticsearch:7.17.4
    container_name: es-master-1

    environment:
      - TZ=Asia/Seoul
      - cluster.name=es-cluster-1
      - node.name=es-master-1
      - discovery.seed_hosts=es-master-1, es-data-1
      - cluster.initial_master_nodes=es-master-1
      - bootstrap.memory_lock=false
      - ES_JAVA_OPTS=-Xms256m -Xmx256m

    ports:
      - 9200:9200

    expose:
      - "9300"

    volumes:
      - ./es-master-1/data:/usr/share/elasticsearch/data/nodes/0
      - ./es-master-1/logs:/usr/share/elasticsearch/logs

  es-data-1:
    image: elasticsearch:7.17.4
    container_name: es-data-1

    environment:
      - TZ=Asia/Seoul
      - cluster.name=es-cluster-1
      - node.name=es-data-1
      - node.master=false
      - node.data=true
      - discovery.seed_hosts=es-master-1, es-data-1
      - cluster.initial_master_nodes=es-master-1
      - bootstrap.memory_lock=false
      - ES_JAVA_OPTS=-Xms256m -Xmx256m

    ports:
      - 9201:9201

    expose:
      - "9301"

    volumes:
      - ./es-data-1/data:/usr/share/elasticsearch/data/nodes/0
      - ./es-data-1/logs:/usr/share/elasticsearch/logs

    depends_on:
      - es-master-1