
FROM            elasticsearch:7.17.2

ENV             TZ Asia/Seoul
ARG             DEBIAN_FRONTEND=noninteractive


# 실행 명령어
# docker run -d -p 9200:9200 --name es01 -e "discovery.type=single-node" elasticsearch:7.17.2
# docker run -d -p 9200:9200 --name es01 -e discovery.type=single-node -e TZ=Asis/Seoul elasticsearch:7.17.2